sudo: required
services:
  - docker

before_install:
  - docker build -t andrzejburzynski/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true andrzejburzynski/docker-react npm run test -- --coverage